src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/source/CosmosDBSourceTask.java

Fix an issue while creating a Lease Container when it does not exists. The current code would not swallow an exception when the status code is 404 when it is the intended behaviour
I would like to increase testability. The current method for creating the lease container is private, and the only way to test it is going through the whole start method. Maybe extract the create lease to another class to make it public?
- References #142

Fixed creating the LeaseContainer when the leaseCollection does not exist

---

src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/source/CosmosDBSourceTask.java

Ensures that contentResponseOnWrite is enabled to use the ChangeFeedProcessorBuilder
Fix an issue when using the ChangeFeedProcessorBuilder that the contentResponseOnWrite is not enabled
- Closes #150

Fix contentResponseOnWriteEnabled

---

doc/README_Source.md
src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/BooleanSetting.java
src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/source/CosmosDBSourceTask.java
src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/source/SourceSettingDefaults.java
src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/source/SourceSettings.java
src/test/java/com/microsoft/azure/cosmosdb/kafka/connect/source/SourceSettingsTest.java

Today the option to start from beginning on the change feed is hard coded to true. A new setting make it possible to set it to false on demand was created
- Closes #164

Create new setting to the change feed

---

src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/Settings.java
src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/sink/SinkSettings.java
src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/source/SourceSettings.java
src/test/java/com/microsoft/azure/cosmosdb/kafka/connect/sink/CosmosDBSinkConnectorConfigTest.java
src/test/java/com/microsoft/azure/cosmosdb/kafka/connect/sink/SinkSettingsTest.java
src/test/java/com/microsoft/azure/cosmosdb/kafka/connect/source/SourceSettingsTest.java

- Ensuring that sink config settings only show up when setting up the sink connector (vice versa for source connector)
- Settings common for both sink and source will show up when setting up either connector
- Some wording changes for setting descriptions
- Minor code style changes
- Closes #174

Making Config properties adhere to Sink or source connectors

---

doc/README_Source.md
src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/source/CosmosDBSourceTask.java
src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/source/SourceSettingDefaults.java
src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/source/SourceSettings.java
src/test/java/com/microsoft/azure/cosmosdb/kafka/connect/source/CosmosDBSourceTaskTest.java

- Setting the message key using the Cosmos DB item ID
- Added a source setting to enable/disable this message key behavior
- Updated docs for info on new source setting
- Closes #159

Adding option to set message key

---

src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/SettingDefaults.java
src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/sink/CosmosDBSinkTask.java
src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/sink/SinkSettingDefaults.java
src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/sink/SinkSettings.java
src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/source/CosmosDBSourceTask.java
src/test/java/com/microsoft/azure/cosmosdb/kafka/connect/sink/CosmosDBSinkTaskTest.java

- Exposed use upsert config to Sink Connector Property to support both Insert and Upsert Operations
- Set default value to false for upsert config
- Set User-Agent for CosmosDB Java client
- Closes #147 #167

Exposed upsert configuration for Sink Connector and added user-agent to cosmosdb java client

---

src/docker/docker-compose.yml
src/docker/startup.ps1
src/docker/startup.sh
src/integration-test/Dockerfile

Remove mounting the custom jars as volume mounts in the Kafka Connect docker container
Use custom docker file to copy the jars into the docker image instead
- Closes #182

Using customer dockerfile instead of volume mounts

---

.github/ISSUE_TEMPLATE/sprint_tracker.md

Add a template for sprint tracking issue type so we can better keep track of sprint adjustments
I am testing moving our notes for sprint tracking to an issue because I'm running out of characters: (

adding a sprint tracker issue type

---

.github/ISSUE_TEMPLATE/sprint_tracker.md

Add the right labels when someone creates a sprint tracker issue type

adding labels to the sprint tracker template

---

doc/README_Source.md
src/docker/resources/source.example.json
src/docker/resources/source.example.properties
src/main/java/com/azure/cosmos/kafka/connect/TopicContainerMap.java
src/main/java/com/azure/cosmos/kafka/connect/source/CosmosDBSourceConfig.java
src/main/java/com/azure/cosmos/kafka/connect/source/CosmosDBSourceConnector.java
src/test/java/com/azure/cosmos/kafka/connect/source/CosmosDBSourceConfigTest.java
src/test/java/com/azure/cosmos/kafka/connect/source/CosmosDBSourceConnectorTest.java
src/test/java/com/azure/cosmos/kafka/connect/source/integration/SourceConnectorIT.java

Removing config container list from source connector since this info can be obtained from topic-container map
Also removed worker name and assigned container since these shouldn't matter to the end user
- Closes #277

Removing unneeded source configs

---

pom.xml
src/main/java/com/azure/cosmos/kafka/connect/sink/CosmosDBSinkConnector.java
src/test/java/com/azure/cosmos/kafka/connect/sink/CosmosDBSinkConnectorTest.java

Implements the `validate` method on CosmosDBSinkConnector
N/A
Changes have accompanying unittests.

Adds validations for CosmosDBSink connector

---

src/main/java/com/azure/cosmos/kafka/connect/CosmosDBConfig.java
src/test/java/com/azure/cosmos/kafka/connect/sink/CosmosDBSinkConfigTest.java

Adds some minor validation on string config properties that should be non empty
N/A
Yes. A unittest was added to verify behavior when empty string is specified.
References #372

MINOR: Add non-empty string validation for string configs

---

doc/README_Sink.md
pom.xml
src/main/java/com/azure/cosmos/kafka/connect/CosmosDBConfig.java
src/main/java/com/azure/cosmos/kafka/connect/sink/CosmosDBSinkConfig.java
src/main/java/com/azure/cosmos/kafka/connect/sink/CosmosDBSinkTask.java
src/main/java/com/azure/cosmos/kafka/connect/source/CosmosDBSourceConfig.java
src/main/java/com/azure/cosmos/kafka/connect/source/CosmosDBSourceTask.java
src/test/java/com/azure/cosmos/kafka/connect/sink/CosmosDBSinkConfigTest.java
src/test/java/com/azure/cosmos/kafka/connect/sink/CosmosDBSinkConnectorConfigTest.java
src/test/java/com/azure/cosmos/kafka/connect/sink/CosmosDBSinkTaskTest.java
src/test/java/com/azure/cosmos/kafka/connect/source/CosmosDBSourceConfigTest.java

As described in #381 , running the connector in INSERT mode can be problematic when the entire batch is retried for a single failed message in batch. The successfully INSERTed messages within the batch are retried and will fail due to duplicate key. This commit thus removes support for INSERT mode and only allows for records to be written with `upsertItem` .
N/A
N/A
After removal of `connect.cosmos.sink.useUpsert` config, `CosmosDBSinkConfig` is essentially empty. I kept it around in case there is the need for separate sink-only configs in the future. But, it could be removed and the sink connector could use the base `CosmosDBConfig` directly.
Closes …

Remove support for sink connector insert mode

---

pom.xml

As described in #380 , there are a number of dependencies pulled in transitively that have CVE issues discovered in Twistlock. This PR aims to remove these dependencies by:
- Bumping `azure-cosmos` version to latest version
- Bumping `azure-core-http-netty` version to latest version
- Explicitly replacing `log4j:log4j:1.2.17` with `io.confluent:confluent-log4j:1.2.17-cp2`
The twistlock scan after applying this PR contains no critical or high severity CVEs
N/A
Verified CVE fixes in Twistlock. Sanity check the connector after applying this PR with scripts in https://github.com/vdesabou/kafka-docker-playground/tree/master/connect/connect-azure-cosmosdb-sink …

CCDB-3949: remove problematic dependencies that have CVE issues

---

.github/workflows/mavenCI.yml
pom.xml
src/test/java/com/azure/cosmos/kafka/connect/sink/StructToJsonMapTest.java

The change increases code coverage slightly by adding a test for `StructToJsonMap`. It also exposes the code coverage artifact in CI for download. An example of result with code coverage artifact is here - https://github.com/ncliang/kafka-connect-cosmosdb/actions/runs/841625044
N/A
This change is only a test change.
N/A

CCDB-3951: Adds tests for StructToJsonMap; also hooks up jacoco code coverage

---

pom.xml
src/main/java/com/azure/cosmos/kafka/connect/sink/CosmosDBSinkTask.java

Bump json-path version to 2.6.0 to pick up fix for CVE-2021-27568. Also, minor tweak to log user data at lower log level.
N/A
no

MINOR: bump json-path to version 2.6.0 to pick up fix for CVE-2021-27568

---

src/main/java/com/azure/cosmos/kafka/connect/sink/CosmosDBSinkTask.java

Minor performance and readability improvement for the log line.
Cursory search through log statements didn't turn up any other instances of calling `toString` in logs. The null check there also isn't necessary as the logging framework can handle logging nulls as expected.
Closes #400

MINOR: minor performance and readability improvement for logging

---

CHANGELOG.md
pom.xml

upgrade log4j2 to 2.16.0 as log4j2 2.15.0 fix was incomplete.
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-45046

upgrade log4j2 to 2.16.0 as 2.15.0 fix was incomplete

---

CHANGELOG.md
pom.xml

DoS attack under certain log4j2 <= 2.1.6.0 config.
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-45105
upgrade to log4j2 2.17.0
release 1.2.3

upgrade log4j2 to 2.17.0

---

CHANGELOG.md
pom.xml

DoS attack under certain log4j2 <= 2.1.6.0 config.
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-45105
upgrade to log4j2 2.17.0
release 1.2.3

release 1.2.3

---

CHANGELOG.md
pom.xml

releasing 1.2.4 which has 2.17.1 log4j2  addressing
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-44832

1.2.4 upgrade to 2.17.1

---

CHANGELOG.md
pom.xml

releasing 1.2.4 which has 2.17.1 log4j2 addressing
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-44832

releasing 1.2.4 which has 2.17.1 log4j2

---

src/main/java/com/azure/cosmos/kafka/connect/sink/StructToJsonMap.java
src/test/java/com/azure/cosmos/kafka/connect/sink/StructToJsonMapTest.java

Solve the problem of not being able to write nullable structs (e.g. typically present in complex Avro Schemas).
Nothing.
Yes a unit test was added to validate the correction of the change.
- References #438

Allow nullable structs + test.

---

README.md
pom.xml
src/main/java/com/azure/cosmos/kafka/connect/CosmosDBConfig.java
src/main/java/com/azure/cosmos/kafka/connect/sink/CosmosDBSinkTask.java
src/test/java/com/azure/cosmos/kafka/connect/sink/CosmosDBSinkTaskTest.java
src/test/java/com/azure/cosmos/kafka/connect/sink/CosmosDBSinkTaskTestNotFails.java

The problem with the current implementation is that one record throws an exception then the connector fails. On Kafka once the record is written it cannot be deleted. So we need a way to skip this record. 
If a Record that we defined as Key is null we get the following error: "The input name '' is invalid. Ensure to provide a unique non-empty string less than '1024' characters." And the connector fails. 
I added a configuration that ensures that if processing fails we log the failed record and continue processing the rest of the stream. 
- References #<issue number> …

Added tolerance into CosmosDBSink

---

src/main/java/com/azure/cosmos/kafka/connect/CosmosDBConfig.java
src/main/java/com/azure/cosmos/kafka/connect/sink/CosmosDBSinkConnector.java
src/main/java/com/azure/cosmos/kafka/connect/source/CosmosDBSourceConnector.java
src/test/java/com/azure/cosmos/kafka/connect/sink/CosmosDBSinkConnectorTest.java

`CosmosDB` endpoint and master key validation logic is the same for both *SINK* connector and *SOURCE* connector, the shared code is moved into `CosmosDBConfig`.
misconfigured `CosmosDB` endpoint or master key for *SOURCE* connector will fail validation.
Yes

Reuse the same cosmosdb endpoint/key validation in source connector

---

src/main/java/com/azure/cosmos/kafka/connect/source/CosmosDBSourceTask.java
src/test/java/com/azure/cosmos/kafka/connect/source/CosmosDBSourceTaskTest.java

Issue:
For record size larger than connect.cosmos.task.buffer.size, they will never be published. 
Fix:
Always try to publish at least one record even if it exceeds the predefined buffer size.

Always return at least one record when exceeds buffer size

---

src/main/java/com/azure/cosmos/kafka/connect/sink/StructToJsonMap.java
src/test/java/com/azure/cosmos/kafka/connect/sink/StructToJsonMapTest.java

Fixes parsing for empty arrays

---

pom.xml
src/main/java/com/azure/cosmos/kafka/connect/sink/CosmosDBSinkTask.java
src/test/java/com/azure/cosmos/kafka/connect/sink/BulkWriterTests.java
src/test/java/com/azure/cosmos/kafka/connect/sink/CosmosDBSinkConnectorTest.java
src/test/java/com/azure/cosmos/kafka/connect/sink/CosmosDBSinkTaskTest.java
src/test/java/com/azure/cosmos/kafka/connect/sink/StructToJsonMapTest.java
src/test/java/com/azure/cosmos/kafka/connect/sink/id/strategy/ProvidedInStrategyTest.java
src/test/java/com/azure/cosmos/kafka/connect/sink/id/strategy/TemplateStrategyTest.java

* Fixed sink bug when using struct type for record value
* Removed guava dependency from test (to avoid security vulnerability)
* Fixes #https://github.com/microsoft/kafka-connect-cosmosdb/issues/493

Fixed sink bug when using struct type for record value

---

CHANGELOG.md
src/main/java/com/azure/cosmos/kafka/connect/source/CosmosDBSourceTask.java
src/test/java/com/azure/cosmos/kafka/connect/source/integration/SourceConnectorIT.java

**Changes included:**
1. Ignore Kafka offset and always depend on ChangeFeedProcessor to track the task progress. 
2. When `connect.cosmos.offset.useLatest = false` :  create changeFeedProcessor with startFromBeginning(true)
3. When `connect.cosmos.offset.useLatest = true`:  create changeFeedProcessor with startFromBeginning(false)
The above change fixed the following issues has been reported by customer:
1. When lease container is not initialized, setting `connect.cosmos.offset.useLatest = true` cause no changes being read
2. When lease container is initialized, setting `connect.cosmos.offset.useLatest = true` cause only one lease being updated to have continuationToken 0
**Tests:**
Run e2e cases with lease container not initialized and `connect.cosmos.offset.useLatest = false`, all the …

SourceConnectorOffset

---

src/main/java/com/azure/cosmos/kafka/connect/sink/BulkWriter.java
src/test/java/com/azure/cosmos/kafka/connect/sink/BulkWriterTests.java

The test was comparing the wrong duplicate item. The hashcode for partition key uses the object hashcode, so it is based on reference. Therefore, changed it to use the hascode of the tostring of the partition key to fix functionality. 

fixed bug in test and fixed hashcode method

---

CHANGELOG.md
pom.xml

release1.10.0

---

CHANGELOG.md
pom.xml
src/main/java/com/azure/cosmos/kafka/connect/source/CosmosDBSourceTask.java
src/test/java/com/azure/cosmos/kafka/connect/source/CosmosDBSourceTaskTest.java

Use the lsn from the item to construct the record offset, by doing this, we can remove the unnecessary lease query request

usingLsnAsTheRecordOffset

---

CHANGELOG.md
pom.xml
src/main/java/com/azure/cosmos/kafka/connect/implementations/CosmosKafkaSchedulers.java
src/main/java/com/azure/cosmos/kafka/connect/source/CosmosDBSourceTask.java
src/test/java/com/azure/cosmos/kafka/connect/source/CosmosDBSourceTaskTest.java

**Issue:**
Post [this](https://github.com/apache/kafka/pull/9669) change in kafka connect framework the connector uses a single thread for both
poll() as well as for stop(). Before that change,
the SourceTask::stop method would be invoked on a separate thread from
the one that did the actual data processing for the task (polling the task
for records, transforming and converting those records, then sending them
to Kafka). After that change, SourceTask::stop() is being invoked on the
same thread that handled data processing for the task. This had the effect
that tasks which blocked indefinitely in the SourceTask::poll method with the expectation
that they could stop blocking when SourceTask::stop
was invoked would no longer be capable of graceful shutdown, and may even
hang forever and the …

fixInfiniteLoopIssueWhenSourceTaskGotCancelled

---

CHANGELOG.md
pom.xml
src/main/java/com/azure/cosmos/kafka/connect/implementations/CosmosClientStore.java
src/main/java/com/azure/cosmos/kafka/connect/source/CosmosDBSourceConfig.java
src/main/java/com/azure/cosmos/kafka/connect/source/CosmosDBSourceConnector.java
src/main/java/com/azure/cosmos/kafka/connect/source/CosmosDBSourceTask.java
src/test/java/com/azure/cosmos/kafka/connect/source/CosmosDBSourceConnectorTest.java
src/test/java/com/azure/cosmos/kafka/connect/source/CosmosDBSourceTaskTest.java

**Issue:**
For source connector, when configured with maxTasks > 1, only 1 tasks will run successfully, others will fail. 
**Root cause:**
currently when there are multiple tasks configured, all of them will try to create the lease container, but only 1 will succeeded, others will fail.
**Fixes**:
Move the lease container creation into `CosmosDBSourceConnector`
**Other changes included:**
During task.stop(), adding some delays for closing cosmosClient as the PartitionProcessor will release the leases in the background.

MoveLeaseContainerCreationIntoConnector

---

CHANGELOG.md
src/main/java/com/azure/cosmos/kafka/connect/sink/BulkWriter.java
src/test/java/com/azure/cosmos/kafka/connect/sink/BulkWriterTests.java
src/test/java/com/azure/cosmos/kafka/connect/sink/integration/SinkConnectorIT.java

Fixed an issue where When using container configured with nested partition key path, bulk writer will fail with 400

fix bulkwriter for container with nested partition key

---

.github/workflows/mavenCI.yml
CHANGELOG.md
pom.xml

- Increasing the cosmos version and prepping for a release
- Increased upload artifacts version to v4 because v3 is deprecated
- Took direct dependency on json smart

1.17.0 Release
