src/main/scala/com/microsoft/azure/cosmosdb/kafka/connect/config/BaseConfig.scala
src/main/scala/com/microsoft/azure/cosmosdb/kafka/connect/config/CosmosDBConfig.scala
src/main/scala/com/microsoft/azure/cosmosdb/kafka/connect/config/CosmosDBConfigConstants.scala
src/main/scala/com/microsoft/azure/cosmosdb/kafka/connect/sink/CosmosDBSinkConnector.scala
src/main/scala/com/microsoft/azure/cosmosdb/kafka/connect/sink/CosmosDBSinkService.scala
src/main/scala/com/microsoft/azure/cosmosdb/kafka/connect/sink/CosmosDBSinkSettings.scala
src/main/scala/com/microsoft/azure/cosmosdb/kafka/connect/sink/CosmosDBSinkTask.scala
src/test/scala/com/microsoft/azure/cosmosdb/kafka/connect/config/CosmosDBConfigTest.scala
src/test/scala/com/microsoft/azure/cosmosdb/kafka/connect/sink/CosmosDBSinkSettingsTest.scala

Added a BaseConfig class, CosmosDBConfigSink and CosmosDBConfigSource and fixed the Sink classes to support this new config.

Add a BaseConfig class, CosmosDBConfigSink and CosmosDBConfigSource

---

build.sbt
src/main/scala/com/microsoft/azure/cosmosdb/kafka/connect/CosmosDBClientSettings.scala
src/main/scala/com/microsoft/azure/cosmosdb/kafka/connect/CosmosDBProvider.scala
src/main/scala/com/microsoft/azure/cosmosdb/kafka/connect/LoggingTrait.scala
src/main/scala/com/microsoft/azure/cosmosdb/kafka/connect/Runner.scala

Intial check-in for inserting records using RxJava and Seperating the Cosmos DB Functionality to reuse it in different places.

Cosmosdb Inserting Records using RxJava

---

Dockerfile

Removing unittests, until we get unittests to work without trying to connect to CosmosDB

Removing unittests

---

pom.xml
src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/source/CosmosDBSourceTask.java

Make the connector used an officially released version of the Azure Cosmos DB Java SDK rather than a pre-release.

Update to Azure Cosmos DB SDK 4.2

---

doc/README_Source.md
src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/Settings.java

Add to the quickstart a way to use docker to get to know the connector

Doc with docker

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/library-scripts/azcli-debian.sh
.devcontainer/library-scripts/confluent-debian.sh
.devcontainer/library-scripts/docker-debian.sh
.devcontainer/post-install.sh
src/integration-test/docker-compose.yml
src/integration-test/startup.ps1

- Adding devcontainer support for the repo (can be setup using Codespaces or VSCode)
- Updating kafka stack to use [confluent supported version](https://github.com/confluentinc/cp-all-in-one)
- Closes #152 
- References #157

Adding devcontainer support

---

pom.xml

- Updating dependencies and plugin properties to latest in pom.xml
- run `mvn clean test` to validate unit tests
- run integration tests to validate app builds properly
- Closes #169

Updated maven plugin dependencies to latest supporting java11

---

src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/Settings.java
src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/sink/SinkSettings.java
src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/source/SourceSettings.java
src/test/java/com/microsoft/azure/cosmosdb/kafka/connect/sink/SinkSettingsTest.java
src/test/java/com/microsoft/azure/cosmosdb/kafka/connect/source/SourceSettingsTest.java

removing pre- and post- processors from the code as these are now redundant since Kafka Connect added SMTs.
Please review and make sure it builds and looks good once deployed in Control Center. For some reason i am getting a really strange error in VS Code, but everything looks good to me. 
- Closes #176

removing pre- and post- processors

---

doc/CosmosDB_Setup.md
doc/README_Sink.md

- Adding small section in Sink docs on how to use SMTs to add TTL for a Cosmos DB item.
- Syncing other doc sections with Source docs
- References #139

Using SMTs to add item TTL

---

.github/ISSUE_TEMPLATE/EngineeringFundChecklist.md

- Add the Tech Lead checklist to the project
- Closes #207

Add engineering checklist (#207)

---

.gitignore
README.md
src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/TopicContainerMap.java
src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/sink/CosmosDBSinkConnector.java
src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/sink/CosmosDBSinkTask.java
src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/sink/SinkSettings.java
src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/source/CosmosDBSourceConnector.java
src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/source/CosmosDBSourceTask.java
src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/source/LinkedTransferQueue.class
src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/source/SourceSettingDefaults.java
src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/source/SourceSettings.java
src/test/java/com/microsoft/azure/cosmosdb/kafka/connect/sink/CosmosDBSinkConnectorConfigTest.java
src/test/java/com/microsoft/azure/cosmosdb/kafka/connect/sink/CosmosDBSinkTaskTest.java
src/test/java/com/microsoft/azure/cosmosdb/kafka/connect/source/CosmosDBSourceConfigTest.java
src/test/java/com/microsoft/azure/cosmosdb/kafka/connect/source/CosmosDBSourceTaskTest.java

major refactor to address the issues raised by sonarlint.
still 3 issues left at the moment, that i do not yet know how to resolve. 
will address those with another PR in the future once we've discussed and found a solution. 
- References #183

addressing sonarlint issues

---

doc/README_Sink.md
src/integration-test/startup.ps1
src/integration-test/startup.sh

Installing InsertUUID SMT in local conf platform setup
Adding setup and config steps for UUID smt in docs
- Closes #144

InsertUUID SMT to auto add IDs, adding guide to docs

---

.github/ISSUE_TEMPLATE/EngineeringFundChecklist.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/checkpoint.md
.github/ISSUE_TEMPLATE/feature_request.md
CONTRIBUTING.md
DEVELOPER_WALKTHROUGH.MD
LICENSE.MD
README.md
doc/README_Sink.md
doc/README_Source.md

Fixing up the markdown linter issues
- Closes #183

Markdown linter

---

src/integration-test/resources/sink.config.json

- [] Code changes
Correcting the field names for the example `sink.config.json` file.

Fixing example config fieldnames

---

.github/PULL_REQUEST_TEMPLATE.md

Adds a section for observability and testing to the PR template in order to keep these top of mind.
- Closes #213 (this will automatically close the issue when the PR closes)
- References #213  (this references the issue but does not close with PR)

Add observabilty and testing callout to PR template

---

.github/workflows/release.yml
pom.xml

- Using Confluent mvn plugin to package the source code in the Confluent [archive format](https://docs.confluent.io/home/connect/confluent-hub/component-archive.html)
- Renaming the release jar for readability
- Closes #202

Confluent packaging

---

src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/sink/CosmosDBSinkTask.java
src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/source/CosmosDBSourceTask.java

Ensure that the resources are setup before closing them
- Closes #190

Add validation in source/sink task close method

---

README.md

Add current release information to the readme
- Closes #229 (this will automatically close the issue when the PR closes)
- References #229 (this references the issue but does not close with PR)

Add release badge to repo readme

---

README.md
src/docker/Dockerfile
src/docker/docker-compose.yml
src/test/java/com/microsoft/azure/cosmosdb/kafka/connect/sink/integration/SinkConnectorIT.java
src/test/java/com/microsoft/azure/cosmosdb/kafka/connect/source/integration/SourceConnectorIT.java

- Add datagen connector to confluent setup 
- Fix name issue with Integration tests
- Readme fixes
N/A

Add datagen connector + other minor fixes

---

src/main/java/com/azure/cosmos/kafka/connect/sink/CosmosDBSinkTask.java
src/main/java/com/azure/cosmos/kafka/connect/sink/CosmosDBWriteException.java
src/main/java/com/azure/cosmos/kafka/connect/source/CosmosDBSourceTask.java

fixing linter issues
NA
NA
Please check that fixing linter issues didn't inadvertently introduce bugs

fixing linter issues

---

.github/workflows/mavenCI.yml
.github/workflows/release.yml
pom.xml
src/test/java/com/azure/cosmos/kafka/connect/sink/integration/SinkConnectorIT.java
src/test/java/com/azure/cosmos/kafka/connect/source/integration/SourceConnectorIT.java

- Updating maven java compile
- Increasing integration test timings so they pass more consistently
N/A

Updating compiler version, integration test timings

---

pom.xml
src/test/java/com/azure/cosmos/kafka/connect/sink/integration/SinkConnectorIT.java
src/test/java/com/azure/cosmos/kafka/connect/source/integration/SourceConnectorIT.java

- Added Integration Tests to validate sink connector class end to end with below supported data formats
- JSON Plain
- JSON with Schema
- AVRO
- loggers to indicate data generation for tests
- NA
- Closes #227

Sink Integration tests for AVRO and schema converter

---

pom.xml
src/test/java/com/azure/cosmos/kafka/connect/source/integration/SourceConnectorIT.java

- Added Integrations tests for Source Connector supporting AVRO and JSON Schema conversion
- Added debug loggers for kafka consumer feed
- IT tests added
- Closes #227

Source Integration tests for AVRO and schema converter

---

pom.xml

Creating a shaded jar to avoid duplicate netty library jars, causing the standalone bug
- Closes #233

Creating shaded jar to support connect standalone

---

.github/ISSUE_TEMPLATE/sprint_tracker.md

small updates to sprint tracker template

---

pom.xml
src/docker/docker-compose.yml
src/main/java/com/azure/cosmos/kafka/connect/source/CosmosDBSourceTask.java

- Fixes errors when source task is closed
- Getting the connector logging working again
- Pom changes to fix Cosmos user agent, shade outputs
- Related #253

Fixing source task close error + other fixes

---

src/docker/.gitignore
src/docker/resources/sink.config.json
src/docker/resources/sink.properties
src/docker/resources/source.config.json
src/docker/resources/source.properties
src/docker/resources/standalone.properties
src/test/.gitignore
src/test/resources/sink.config.json
src/test/resources/source.config.json

I removed the Config files without realizing in my last PR, using gitignore is harder than it seems :/
will make another pr to correct the gitignore behavior
- References #279

Adding back configs

---

.github/ISSUE_TEMPLATE/epic.md

Adding a template for epic issue type

---

.github/ISSUE_TEMPLATE/epic.md

You have to have this top information in order for GH to understand it

Add epic definition to epic template

---

doc/README_Sink.md
doc/README_Source.md

- Source connector docs for JSON to Schema data types mapping 
- Sink connector docs for Schema to JSON data types mapping
NA
NA
- Closes #332

Document supported datatypes for sink and source connector

---

README.md

is this where we want it? should it go under another section?
- Closes #334

adding exactly once verbiage

---

README.md

Probably should have looked this up the first time

update proper semantics names in readme

---

.github/workflows/release.yml

- Added project .zip archive to release assets as part of GitHub workflow
NA
NA

Updated release assets

---

pom.xml

Added support logo, moved description to paragraph, small edits

update pom.xml to support manifest edits

---

src/test/java/com/azure/cosmos/kafka/connect/sink/StructToJsonMapTest.java

addressing some minor linting issues found in tests

"linting issues in tests"

---

pom.xml

version bump 1.0.0-beta.10

---

pom.xml

1.1.0 release

---

pom.xml

release 1.1.0

---

CHANGELOG.md

Added changelog file to keep track of changes across different releases for both sink and source connectors.

Added changelog file to keep track of changes to kafka connector for both sink and source connectors

---

pom.xml

Version bump to 1.2.0

---

CHANGELOG.md

Updating the changelogs

---

src/main/java/com/azure/cosmos/kafka/connect/sink/CosmosDBSinkConfig.java
src/main/java/com/azure/cosmos/kafka/connect/source/CosmosDBSourceTask.java
src/test/java/com/azure/cosmos/kafka/connect/sink/CosmosDBSinkConnectorTest.java
src/test/java/com/azure/cosmos/kafka/connect/sink/CosmosDBSinkTaskTest.java
src/test/java/com/azure/cosmos/kafka/connect/source/CosmosDBSourceConnectorTest.java

1. Version bump-1.2.0 dev to main
2. CosmosDB version increase 4.15.0 -> 4.21.1

Version bump-1.2.0 dev to main

---

CHANGELOG.md
pom.xml

merging dev to main: 1.12.1 release

merge dev to main: 1.12.1 release

---

CHANGELOG.md
pom.xml

merge dev to main for 1.2.2 release

merge dev to main for 1.2.2 release

---

CHANGELOG.md
pom.xml

Version bump + changelog changes

Kafka connect cosmos db 1.2.5 release

---

CHANGELOG.md
pom.xml
src/main/java/com/azure/cosmos/kafka/connect/sink/StructToJsonMap.java
src/test/java/com/azure/cosmos/kafka/connect/sink/StructToJsonMapTest.java

* Release 1.2.5 version update and changelog.
* Also includes nullable struct fix

Release 1.2.5 version update

---

CHANGELOG.md
README.md
pom.xml
src/main/java/com/azure/cosmos/kafka/connect/CosmosDBConfig.java
src/main/java/com/azure/cosmos/kafka/connect/sink/CosmosDBSinkConnector.java
src/main/java/com/azure/cosmos/kafka/connect/sink/CosmosDBSinkTask.java
src/main/java/com/azure/cosmos/kafka/connect/sink/StructToJsonMap.java
src/main/java/com/azure/cosmos/kafka/connect/source/CosmosDBSourceConnector.java
src/test/java/com/azure/cosmos/kafka/connect/sink/CosmosDBSinkConnectorTest.java
src/test/java/com/azure/cosmos/kafka/connect/sink/CosmosDBSinkTaskTestNotFails.java
src/test/java/com/azure/cosmos/kafka/connect/sink/StructToJsonMapTest.java

Merging latest dev to main

---

src/main/java/com/azure/cosmos/kafka/connect/source/JsonToStruct.java

Fix bug
- Closes #418  (this will automatically close the issue when the PR closes)

Fix parsing of 64 bit values

---

CHANGELOG.md
pom.xml

* Updated versions for release of kafka-connect to 1.3.1
* Updated changelog

Updated versions for release of kafka-connect to 1.3.1

---

CHANGELOG.md
pom.xml
src/main/java/com/azure/cosmos/kafka/connect/source/JsonToStruct.java

* Merging dev to main for latest release - 1.3.1

Merging dev to main for latest release - 1.3.1

---

src/main/java/com/azure/cosmos/kafka/connect/sink/CosmosDBSinkTask.java
src/main/java/com/azure/cosmos/kafka/connect/source/CosmosDBSourceTask.java
src/main/java/com/azure/cosmos/kafka/connect/source/JsonToStruct.java

To address logging of (potentially) sensitive user data raised in #454 .
Sensitive user data was omitted from being logged
- Closes #454

CCDB-4643,CCDB-4644: logging changes to elide sensitive user data

---

CHANGELOG.md
src/main/java/com/azure/cosmos/kafka/connect/CosmosDBConfig.java
src/test/java/com/azure/cosmos/kafka/connect/CosmosConfigTest.java
src/test/java/com/azure/cosmos/kafka/connect/sink/CosmosDBSinkConnectorTest.java

Bug fix.
Customer is getting "Invalid endpoint: Invalid host: xxx" exception even though the endpoint is valid.

remove endpoint validation

---

CHANGELOG.md
pom.xml

Version bump for release 1.3.2 Kafka Connector

Version bump for release 1.3.2

---

CHANGELOG.md
pom.xml

Version bump for release 1.4.0

Version bump for release 1.4.0

---

doc/README_Source.md
src/main/java/com/azure/cosmos/kafka/connect/source/CosmosDBSourceConnector.java

* Updated source connector readme with tasks.max property limitation.
* Fixes discussion #470

Updated source connector readme with tasks.max property limitation

---

CHANGELOG.md
pom.xml

Version bump to 1.5.0, new release

Version bump to 1.5.0, new release

---

CHANGELOG.md
src/main/java/com/azure/cosmos/kafka/connect/CosmosDBConfig.java
src/main/java/com/azure/cosmos/kafka/connect/sink/CosmosDBSinkTask.java
src/main/java/com/azure/cosmos/kafka/connect/source/CosmosDBSourceTask.java
src/test/java/com/azure/cosmos/kafka/connect/sink/CosmosDBSinkConfigTest.java
src/test/java/com/azure/cosmos/kafka/connect/source/CosmosDBSourceConfigTest.java

1. Add gateway support
2. Add connectionSharing support for direct mode

enable gateway support

---

CHANGELOG.md
pom.xml

release 1.6.0

---

doc/README_Sink.md

Updated sink connector docs with connection sharing information

Updated sink connector docs with connection sharing information

---

CHANGELOG.md
pom.xml

Fixing security vulnerabilities
- Updated the azure-cosmos version to 4.41.0
- Updated the kafka-connect-client to 4.0.3
- Added guava as a dependency

Fixing security vulnerabilities

---

pom.xml

Updating Kafka connector version for release - 1.7.0

---

CHANGELOG.md
pom.xml

Release kafka connect 1.7.1

---

CHANGELOG.md
pom.xml
src/main/java/com/azure/cosmos/kafka/connect/sink/CosmosDBSinkTask.java
src/main/java/com/azure/cosmos/kafka/connect/sink/StructToJsonMap.java
src/test/java/com/azure/cosmos/kafka/connect/sink/CosmosDBSinkTaskTest.java
src/test/java/com/azure/cosmos/kafka/connect/sink/StructToJsonMapTest.java

* Fixes #507 
* Fixes security vulnerability in json-path version
* Updated azure-cosmos to 4.42.0

Fixed issue with maps with nested struct types for sink task

---

CHANGELOG.md
pom.xml

Version update to 1.8.0

---

CHANGELOG.md
src/main/java/com/azure/cosmos/kafka/connect/source/CosmosDBSourceTask.java
src/test/java/com/azure/cosmos/kafka/connect/source/CosmosDBSourceTaskTest.java

Return from `Poll` method once all records have been processed from the changeFeedProcessor batches.

ReturnFromPollMethodOnceAllRecordsCollectedFromHandleChanges

---

CHANGELOG.md
pom.xml

- Update azure-cosmos to 4.46.0
- kafka SDK release 1.9.0

release1.9.0

---

CHANGELOG.md

Resolve comments from PR https://github.com/microsoft/kafka-connect-cosmosdb/pull/519

resolveCommentsForRelease1.9.0

---

src/test/java/com/azure/cosmos/kafka/connect/sink/integration/SinkConnectorIT.java

Fixed typo in configuration for tests. 

fixed typo

---

CHANGELOG.md
pom.xml

Updated version and changelog for release 1.11.0

Updated version and changelog for release 1.11.0

---

CHANGELOG.md
pom.xml

* Release kafka connect 1.12.0
* Updated azure-cosmos to 4.53.1

Release kafka connect 1.12.0

---

CHANGELOG.md
pom.xml

Merging dev to main

---

pom.xml

Updated version of kafka connect cosmos db in pom.xml

Updated version of kafka connect cosmos db in pom.xml

---

CHANGELOG.md
pom.xml
src/main/java/com/azure/cosmos/kafka/connect/sink/CosmosDBSinkTask.java
src/main/java/com/azure/cosmos/kafka/connect/source/CosmosDBSourceTask.java

Changes:
1. Add more debug level logs in source connector
2. Adding worker name in the userAgent
3. Fixed NullPointerException when the value of sinkRecord is null in trace log
4. Close cosmos client properly when sink task is closed 
5. Prepare release of 1.14.0

Add more log details for source connector

---

CHANGELOG.md
pom.xml
src/main/java/com/azure/cosmos/kafka/connect/source/CosmosDBSourceTask.java
src/test/java/com/azure/cosmos/kafka/connect/source/CosmosDBSourceTaskTest.java

FixNullPointerException + test + version update

fixNullPointerException

---

.github/workflows/codeql.yml
src/test/java/com/azure/cosmos/kafka/connect/source/CosmosDBSourceTaskTest.java

AddingCodeQLYamlFile

---

CHANGELOG.md
pom.xml

Release1.14.2

---

pom.xml

Upgrade cosmos version to 4.58.0 to also upgrade azure core netty version. 

Upgrade Cosmos to 4.58.0

---

CHANGELOG.md
pom.xml

15.0 release

---

CHANGELOG.md

Update Release Date

---

.github/workflows/mavenCI.yml
.github/workflows/release.yml
CHANGELOG.md
pom.xml

Kafka Connector Release 1.16 and increase cosmos version to 4.65.0

Release 1.16

---

.github/workflows/mavenCI.yml
.github/workflows/release.yml
src/docker/startup.ps1
src/docker/startup.sh

Update release gh action
